### ISSUE TITLE
issue when intersected pattern

### ISSUE THREAD

**Issue by emadhegab** [freesuraj/SPPatternLock#1]
hi i noticed that when you make a pattern like (3564) which mean that the draw line will get intersected with a circle that had been touched before.. it never match on confirm
so i've added some code you may want to added it to your code :)

change - (NSNumber *)patternToUniqueId method to 
- (NSNumber *)patternToUniqueId
  {
  NSArray *copy = [self.cellsInOrder copy];
  NSInteger index = [copy count] - 1;
  for (id object in [copy reverseObjectEnumerator]) {
      if ([self.cellsInOrder indexOfObject:object inRange:NSMakeRange(0, index)] != NSNotFound) {
          [self.cellsInOrder removeObjectAtIndex:index];
      }
      index--;
  }
  
  long finalNumber = 0;
  long thisNum;
  for(int i = self.cellsInOrder.count - 1 ; i >= 0 ; i--){
      thisNum = ([[self.cellsInOrder objectAtIndex:i] integerValue] + 1) \* pow(10, (self.cellsInOrder.count - i - 1));
      finalNumber = finalNumber + thisNum;
  }
  return @(finalNumber);
  }

Best regards

**Comment by freesuraj** [comment]
Thanks for the report. Will take a look and update it.

**Comment by freesuraj** [comment]
Hi Emadhegab,

First of all thanks for trying it out, and pointing issues in it. BTW, I've revamped the project and added a lot of customisable features.

Could you have a look at the latest version, and if you find issues, please feel free to send pull requests for merge.

Cheers, 
Suraj
