### ISSUE TITLE
how can i erase the last line if not connected to point?

### ISSUE THREAD

**Issue by mankarth004** [freesuraj/SPPatternLock#4]
I want to erase the last line if that is perfectly not connected to the point. so that it looks much better.
![simulator screen shot 04-may-2016 4 52 34 pm](https://cloud.githubusercontent.com/assets/7057881/15012730/aa6decfc-1218-11e6-82f7-3238d1ad0da6.png)

**Comment by freesuraj** [comment]
Hi Mankarth,

Sorry  I was not following the issues. I hope you have managed to figure it out now.

BTW, I have revamped SPPatternLock using swift3 with a lot of customisable features. I hope you can have a look at it and please let me know of any issues. 

Thank you for your support.

**Comment by mankarth004** [comment]
Oh, thanks for the reply..Sure vl look into that.
