### ISSUE TITLE
using Cocoapod 

### ISSUE THREAD

**Issue by dimohamdy** [freesuraj/SPPatternLock#7]
I have a problem when using pod in can't access 
`        let config = LockScreen.Config()
`
 and get this error

> Cannot invoke value of type 'LockScreen.Config.Type' with argument list '()'

**Comment by freesuraj** [comment]
Hi Dimo,

Thanks for raising the issue. That was indeed a valid issue. Not having a default public initializer for `Config` struct was the reason. It has been fixed and updated in the latest version (2.0.2).

You can write a specific version by using following in your Podfile
`pod 'SPPatternLock', '~> 2.0.2'`

Best,
Suraj

**Comment by dimohamdy** [comment]
@freesuraj  thanks for fast reply and fixing issue
