### ISSUE TITLE
wrong sequence

### ISSUE THREAD

**Issue by dimohamdy** [freesuraj/SPPatternLock#8]
@freesuraj 
![image_uploaded_from_ios__4_](https://cloud.githubusercontent.com/assets/1476754/25635483/8f6bd4d0-2f7e-11e7-9122-684914e32c4a.png)

when you connect all nodes in pattern and try to drag then you get this wrong sequence
i will fix it in non complex mode by remove all duplicated numbers but how i can fix it in complex mode

**Comment by freesuraj** [comment]
Hi Ahmed,
Could you provide a test case for this issue? Is the uniqueID generated not unique? What's the main issue here?

**Comment by dimohamdy** [comment]
test case 
1- disable complex type
2- i make pattern size 3*3
3- try to draw pattern that contain all nodes and in the last node and try to drag to any other node

Expect the the  uniqueID length is only 9 
but the real the length of  uniqueID is very big

**Comment by freesuraj** [comment]
If you look at the function that generates `uniqueId`, you'd know why the number is super big. It's actually by design. But I agree we could probably come up with a way to make it unique while not making the value as big.
